# Uncomment this line to define a global platform for your project

use_frameworks!

target 'DDKitDemo' do
  platform :ios, '8.0'
  pod 'JSONModel'
  pod 'Masonry'
end

target 'DDUIKit' do
  platform :ios, '8.0'
  pod 'Masonry'
  pod 'JSONModel'
end

target 'DDUIKitOSX' do
  pod 'Masonry'
  pod 'JSONModel'
end
