# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DDKitDemo' do
  # use_frameworks!
  pod 'JSONModel'
  pod 'Masonry'
end

target 'DDKit' do
  use_frameworks!
  pod 'Masonry'
  pod 'JSONModel'
end
