
$projectName = "DDKitDemo"
$scheme = "DDUIKit"
$PROJECT_NAME = $projectName
$PRODUCT_DIR = "Product"
$CONFIGURATION = "Release"
$IOS_OUTPUTFOLDER = "#{$PRODUCT_DIR}/Release-iOS"
$MACOS_OUTPUTFOLDER = "#{$PRODUCT_DIR}/Release-macOS"
$ios_version = "10.2"

task :default do |t|
  sh "mkdir -p \"#{$IOS_OUTPUTFOLDER}\""

	sh "xcodebuild -workspace #{$projectName}.xcworkspace -scheme #{$scheme} -configuration Release -sdk iphoneos#{$ios_version} clean"
  sh "xcodebuild -workspace #{$projectName}.xcworkspace -scheme #{$scheme} -configuration Release -sdk iphoneos#{$ios_version} SYMROOT=$(pwd)/Build"
  sh "xcodebuild -workspace #{$projectName}.xcworkspace -scheme #{$scheme} -configuration Release -sdk iphonesimulator#{$ios_version} SYMROOT=$(pwd)/Build"

  sh "cp -R \"Build/#{$CONFIGURATION}-iphoneos/#{$scheme}.framework\" \"#{$IOS_OUTPUTFOLDER}/\""

  sh "lipo -create -output \"#{$IOS_OUTPUTFOLDER}/#{$scheme}.framework/#{$scheme}\" \"Build/#{$CONFIGURATION}-iphonesimulator/#{$scheme}.framework/#{$scheme}\" \"Build/#{$CONFIGURATION}-iphoneos/#{$scheme}.framework/#{$scheme}\""

end

task :macos do |t|
  sh "xcodebuild -workspace #{$projectName}.xcworkspace -scheme #{$scheme}OSX -configuration Release -sdk macosx10.12 SYMROOT=$(pwd)/Build"
  sh "rm -r \"#{$MACOS_OUTPUTFOLDER}/\""
  sh "mkdir -p \"#{$MACOS_OUTPUTFOLDER}\""
  sh "cp -R \"#{$PRODUCT_DIR}/#{$CONFIGURATION}/#{$scheme}.framework\" \"#{$MACOS_OUTPUTFOLDER}/\""
end
