
$projectName = "DDKitDemo"
$scheme = "DDUIKit"
$PROJECT_NAME = $projectName
$BUILD_DIR = "Build"
$CONFIGURATION = "Release"
$IOS_OUTPUTFOLDER = "#{$BUILD_DIR}/Release-iOS"
$MACOS_OUTPUTFOLDER = "#{$BUILD_DIR}/Release-macOS"

task :default do |t|
  sh "mkdir -p \"#{$IOS_OUTPUTFOLDER}\""

	sh "xcodebuild -workspace #{$projectName}.xcworkspace -scheme #{$scheme} -configuration Release -sdk iphoneos10.1 clean"
  sh "xcodebuild -workspace #{$projectName}.xcworkspace -scheme #{$scheme} -configuration Release -sdk iphoneos10.1 SYMROOT=$(pwd)/Build"
  sh "xcodebuild -workspace #{$projectName}.xcworkspace -scheme #{$scheme} -configuration Release -sdk iphonesimulator10.1 SYMROOT=$(pwd)/Build"

  sh "cp -R \"#{$BUILD_DIR}/#{$CONFIGURATION}-iphoneos/#{$scheme}.framework\" \"#{$IOS_OUTPUTFOLDER}/\""

  sh "lipo -create -output \"#{$IOS_OUTPUTFOLDER}/#{$scheme}.framework/#{$scheme}\" \"#{$BUILD_DIR}/#{$CONFIGURATION}-iphonesimulator/#{$scheme}.framework/#{$scheme}\" \"#{$BUILD_DIR}/#{$CONFIGURATION}-iphoneos/#{$scheme}.framework/#{$scheme}\""

end

task :macos do |t|
  sh "mkdir -p \"#{$MACOS_OUTPUTFOLDER}\""
  sh "xcodebuild -workspace #{$projectName}.xcworkspace -scheme #{$scheme}OSX -configuration Release -sdk macosx10.12 SYMROOT=$(pwd)/Build"
  sh "cp -R \"#{$BUILD_DIR}/#{$CONFIGURATION}/#{$scheme}.framework\" \"#{$MACOS_OUTPUTFOLDER}/\""
end
